# copy to ~/.config/nix/nix.conf

# allow flakes
extra-experimental-features = nix-command flakes

# support nix-ros-overlay features
extra-experimental-features = auto-allocate-uids configurable-impure-env
